arrowParens: avoid
bracketSpacing: true
endOfLine: auto
importOrder: ['<THIRD_PARTY_MODULES>', '^[./]']
importOrderParserPlugins: ['typescript']
importOrderSeparation: true
importOrderSortSpecifiers: true
printWidth: 80
singleQuote: true
tabWidth: 2
trailingComma: all

overrides:
  - files: '*.sol'
    options:
      tabWidth: 4
