/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../common";

export interface ICoinFlipInterface extends utils.Interface {
  functions: {
    "consecutiveWins()": FunctionFragment;
    "flip(bool)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "consecutiveWins" | "flip"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "consecutiveWins",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "flip", values: [boolean]): string;

  decodeFunctionResult(
    functionFragment: "consecutiveWins",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "flip", data: BytesLike): Result;

  events: {};
}

export interface ICoinFlip extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ICoinFlipInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    consecutiveWins(overrides?: CallOverrides): Promise<[BigNumber]>;

    flip(
      _guess: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  consecutiveWins(overrides?: CallOverrides): Promise<BigNumber>;

  flip(
    _guess: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    consecutiveWins(overrides?: CallOverrides): Promise<BigNumber>;

    flip(_guess: boolean, overrides?: CallOverrides): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    consecutiveWins(overrides?: CallOverrides): Promise<BigNumber>;

    flip(
      _guess: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    consecutiveWins(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    flip(
      _guess: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
