/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ICoinFlip,
  ICoinFlipInterface,
} from "../../../ethernaut/Ethernaut.sol/ICoinFlip";

const _abi = [
  {
    inputs: [],
    name: "consecutiveWins",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bool",
        name: "_guess",
        type: "bool",
      },
    ],
    name: "flip",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ICoinFlip__factory {
  static readonly abi = _abi;
  static createInterface(): ICoinFlipInterface {
    return new utils.Interface(_abi) as ICoinFlipInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICoinFlip {
    return new Contract(address, _abi, signerOrProvider) as ICoinFlip;
  }
}
