/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Telephone__factory } from "./Telephone__factory";
export { TelephoneAttack__factory } from "./TelephoneAttack__factory";
