/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Signer,
  utils,
  Contract,
  ContractFactory,
  BytesLike,
  Overrides,
} from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { Privacy, PrivacyInterface } from "../../privacy/Privacy";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32[3]",
        name: "_data",
        type: "bytes32[3]",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "ID",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "locked",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes16",
        name: "_key",
        type: "bytes16",
      },
    ],
    name: "unlock",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405260016000806101000a81548160ff02191690831515021790555042600155600a600260006101000a81548160ff021916908360ff16021790555060ff600260016101000a81548160ff021916908360ff160217905550426002806101000a81548161ffff021916908361ffff16021790555034801561008257600080fd5b506040516102a13803806102a1833981810160405260608110156100a557600080fd5b81019080919050508060039060036100be9291906100c5565b5050610122565b82600381019282156100f4579160200282015b828111156100f35782518255916020019190600101906100d8565b5b5090506101019190610105565b5090565b5b8082111561011e576000816000905550600101610106565b5090565b610170806101316000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c8063b3cea21714610046578063cf30901214610064578063e1afb08c14610084575b600080fd5b61004e6100c5565b6040518082815260200191505060405180910390f35b61006c6100cb565b60405180821515815260200191505060405180910390f35b6100c36004803603602081101561009a57600080fd5b8101908080356fffffffffffffffffffffffffffffffff191690602001909291905050506100dc565b005b60015481565b60008054906101000a900460ff1681565b60036002600381106100ea57fe5b01546fffffffffffffffffffffffffffffffff1916816fffffffffffffffffffffffffffffffff19161461011d57600080fd5b60008060006101000a81548160ff0219169083151502179055505056fea2646970667358221220d90dce56036c59102842e4119c9d844cc8f43af8ed3b75d3ccadee01a2f2991664736f6c634300060c0033";

type PrivacyConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: PrivacyConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Privacy__factory extends ContractFactory {
  constructor(...args: PrivacyConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    _data: [BytesLike, BytesLike, BytesLike],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<Privacy> {
    return super.deploy(_data, overrides || {}) as Promise<Privacy>;
  }
  override getDeployTransaction(
    _data: [BytesLike, BytesLike, BytesLike],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(_data, overrides || {});
  }
  override attach(address: string): Privacy {
    return super.attach(address) as Privacy;
  }
  override connect(signer: Signer): Privacy__factory {
    return super.connect(signer) as Privacy__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): PrivacyInterface {
    return new utils.Interface(_abi) as PrivacyInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Privacy {
    return new Contract(address, _abi, signerOrProvider) as Privacy;
  }
}
