/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ethernaut",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ethernaut__factory>;
    getContractFactory(
      name: "ICoinFlip",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ICoinFlip__factory>;
    getContractFactory(
      name: "ForceAttack",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ForceAttack__factory>;
    getContractFactory(
      name: "King",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.King__factory>;
    getContractFactory(
      name: "KingAttacker",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.KingAttacker__factory>;
    getContractFactory(
      name: "Telephone",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Telephone__factory>;
    getContractFactory(
      name: "TelephoneAttack",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TelephoneAttack__factory>;

    getContractAt(
      name: "Ethernaut",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Ethernaut>;
    getContractAt(
      name: "ICoinFlip",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ICoinFlip>;
    getContractAt(
      name: "ForceAttack",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ForceAttack>;
    getContractAt(
      name: "King",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.King>;
    getContractAt(
      name: "KingAttacker",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.KingAttacker>;
    getContractAt(
      name: "Telephone",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Telephone>;
    getContractAt(
      name: "TelephoneAttack",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.TelephoneAttack>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
