/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { King__factory } from "./King__factory";
export { KingAttacker__factory } from "./KingAttacker__factory";
