/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  KingAttacker,
  KingAttackerInterface,
} from "../../king/KingAttacker";

const _abi = [
  {
    inputs: [
      {
        internalType: "address payable",
        name: "target",
        type: "address",
      },
    ],
    name: "execute",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506101fc806100206000396000f3fe60806040526004361061001e5760003560e01c80634b64e49214610023575b600080fd5b6100366100313660046101b2565b610038565b005b73ffffffffffffffffffffffffffffffffffffffff81166100a05760405162461bcd60e51b815260206004820152600a60248201527f626164207461726765740000000000000000000000000000000000000000000060448201526064015b60405180910390fd5b600034116100f05760405162461bcd60e51b815260206004820152600860248201527f6e656564206574680000000000000000000000000000000000000000000000006044820152606401610097565b6100fa8134610149565b6101465760405162461bcd60e51b815260206004820152600960248201527f73656e64206661696c00000000000000000000000000000000000000000000006044820152606401610097565b50565b60008273ffffffffffffffffffffffffffffffffffffffff168260405160006040518083038185875af1925050503d80600081146101a3576040519150601f19603f3d011682016040523d82523d6000602084013e6101a8565b606091505b5090949350505050565b6000602082840312156101c457600080fd5b813573ffffffffffffffffffffffffffffffffffffffff811681146101e857600080fd5b939250505056fea164736f6c634300080d000a";

type KingAttackerConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: KingAttackerConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class KingAttacker__factory extends ContractFactory {
  constructor(...args: KingAttackerConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<KingAttacker> {
    return super.deploy(overrides || {}) as Promise<KingAttacker>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): KingAttacker {
    return super.attach(address) as KingAttacker;
  }
  override connect(signer: Signer): KingAttacker__factory {
    return super.connect(signer) as KingAttacker__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): KingAttackerInterface {
    return new utils.Interface(_abi) as KingAttackerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): KingAttacker {
    return new Contract(address, _abi, signerOrProvider) as KingAttacker;
  }
}
