/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as elevatorSol from "./Elevator.sol";
export type { elevatorSol };
import type * as elevatorAttackerSol from "./ElevatorAttacker.sol";
export type { elevatorAttackerSol };
