/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { KingAttack__factory } from "./KingAttack__factory";
export { KingAttacker__factory } from "./KingAttacker__factory";
